# This workflow will install node dependencies, cache them, and run tests for different Node.js versions.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: [ "sub" ]
  pull_request:
    branches: [ "sub" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Supported Node.js versions

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Node.js environment
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Debugging: List installed dependencies (optional)
    - name: List installed dependencies
      run: npm list

    # Step 5: Debugging: Show test directory contents (optional)
    - name: Show test directory contents
      run: ls -R tests/

    # Step 6: Build the source code (if applicable)
    - name: Build the source code
      run: npm run build --if-present

    # Step 7: Run the tests
    - name: Run tests
      run: npx jest tests/assessmentRoutes2.test.js 
